### Insert the jwt received from login response as auth bearer token
POST http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQwODU5NTcsImlzcyI6IjE2In0.1QgCIH59Xb3GswjRAvUTKgZ1lA4kr_s4YNlLEExojZw
###
GET http://localhost:3000/api/v1/user?id=8
Content-Type: application/json

{
}
###
GET http://localhost:3000/api/v1/user/all
Content-Type: application/json

{
}
###

POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "1234",
  "name": "test1",
  "access_type": "1"
}
###

POST http://localhost:3000/api/v1/user/deregister
Content-Type: application/json

{
  "email": "test1@example.com"
}
###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "1234"
}
### password value is the new password
POST http://localhost:3000/api/v1/user/changepassword
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "654321"
}
### name value is the new name
POST http://localhost:3000/api/v1/user/changename
Content-Type: application/json

{
  "email": "bob@test.com",
  "name": "newBobby"
}
###