version: "1"

services:
  question-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/questions
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017"