name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        working-directory: ./frontend
        run: yarn
      - name: Lint
        working-directory: ./frontend
        run: npx eslint .
      - name: Build
        working-directory: ./frontend
        run: "yarn build"
  user-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go 1.21.0
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.0"
          cache-dependency-path: ./user-service/*.sum

      - name: Test
        working-directory: ./user-service
        run: go test -v ./...
      - name: Build
        working-directory: ./user-service
        run: go build
